FROM ollama/ollama:latest

RUN apt-get update && apt-get install -y bash curl && apt-get clean

COPY compose/entrypoint /entrypoint
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /entrypoint

ENTRYPOINT ["/entrypoint"]
