#!/usr/bin/env bash

set -e

DEFAULT_MODULE_NAME=src.main
DEFAULT_VARIABLE_NAME=app

MODULE_NAME=${MODULE_NAME:-$DEFAULT_MODULE_NAME}
VARIABLE_NAME=${VARIABLE_NAME:-$DEFAULT_VARIABLE_NAME}
APP_MODULE=${APP_MODULE:-"$MODULE_NAME:$VARIABLE_NAME"}

DEFAULT_GUNICORN_CONF=config/gunicorn_conf.py
GUNICORN_CONF=${GUNICORN_CONF:-$DEFAULT_GUNICORN_CONF}
WORKER_CLASS=${WORKER_CLASS:-"uvicorn.workers.UvicornWorker"}

if [ "$DEBUG" == "True" ]; then
  echo "Running in development mode with reload..."
  uvicorn "$APP_MODULE" --reload --reload-dir /app --host 0.0.0.0 --port 8000
else
  echo "Running in production mode with gunicorn..."
  gunicorn --forwarded-allow-ips "*" -k "$WORKER_CLASS" -c "$GUNICORN_CONF" "$APP_MODULE"
fi
