x-base: &base
  build:
    context: .
    dockerfile: ./compose/Dockerfile
  depends_on:
    - postgres
  volumes:
    - ./src/:/app/src
  env_file:
    - .env
  networks:
    - snipline_net

services:

  app:
    <<: *base
    image: app
    container_name: app
    ports:
      - "8000:8000"
    command: /start
  
  runner:
    <<: *base
    image: runner
    container_name: runner
    command: ["python", "-m", "src.runner"]

  postgres:
    image: postgres:17
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - snipline_net
    ports:
    - "5432:5432"
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - snipline_net
    volumes:
      - redis_volume:/data


volumes:
  postgres_data:
  redis_volume:

networks:
  snipline_net:
    driver: bridge
  
