version: '3.8'

services:
  app:
    build:
      context: .
    container_name: parser
    shm_size: '1gb'
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - snipline_net
    command: ["uv", "run", "main.py"]

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - snipline_net
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  snipline_net:
    external: true